# This is a basic workflow that is manually triggered

name: Syn Repos

# Controls when the action will run
on:
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "sync"
  sync:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Checkout source repo
      run: |
        git clone https://${{ env.ORG_NAME }}:${{ env.GITHUB_TOKEN }}@github.com/${{ env.ORG_NAME }}/pub-labs-em7lic-auto.git
        cd labs-em7lic-test
        git config user.email \<\>
        git config user.name "Wassim Tout"
        git remote add ${{ env.ORIGINAL_REPO_NAME }} https://${{ env.ORG_NAME }}:${{ env.GITHUB_TOKEN }}@github.com/${{ env.ORIGINAL_REPO_NAME }}.git
        git remote update
        git merge ${{ env.ORIGINAL_REPO_NAME }}/master --allow-unrelated-histories -m 'Synching with private work repo'
        git push origin master
      env:
        GITHUB_TOKEN: ${{ secrets.WASS }}
        ORIGINAL_REPO_NAME: ${{ github.event.repository.name }}
        ORG_NAME: wtout
